// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SFTPTransferCompletePayload 传输完成事件的载荷。
 */
export class SFTPTransferCompletePayload {
    /**
     * 所属 SSH 会话 ID
     */
    "sessionId": string;

    /**
     * 本次传输的唯一 ID
     */
    "transferId": string;

    /**
     * 是否成功
     */
    "success": boolean;

    /**
     * 失败原因（成功时为空）
     */
    "error": string;

    /** Creates a new SFTPTransferCompletePayload instance. */
    constructor($$source: Partial<SFTPTransferCompletePayload> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("transferId" in $$source)) {
            this["transferId"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPTransferCompletePayload instance from a string or object.
     */
    static createFrom($$source: any = {}): SFTPTransferCompletePayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SFTPTransferCompletePayload($$parsedSource as Partial<SFTPTransferCompletePayload>);
    }
}

/**
 * SFTPTransferProgressPayload 传输进度事件的载荷。
 */
export class SFTPTransferProgressPayload {
    /**
     * 所属 SSH 会话 ID
     */
    "sessionId": string;

    /**
     * 本次传输的唯一 ID（前端生成）
     */
    "transferId": string;

    /**
     * 文件名（不含路径）
     */
    "filename": string;

    /**
     * 已传输字节数
     */
    "transferred": number;

    /**
     * 文件总字节数
     */
    "total": number;

    /** Creates a new SFTPTransferProgressPayload instance. */
    constructor($$source: Partial<SFTPTransferProgressPayload> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("transferId" in $$source)) {
            this["transferId"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("transferred" in $$source)) {
            this["transferred"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPTransferProgressPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): SFTPTransferProgressPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SFTPTransferProgressPayload($$parsedSource as Partial<SFTPTransferProgressPayload>);
    }
}

export class SSHClosedPayload {
    "id": string;

    /** Creates a new SSHClosedPayload instance. */
    constructor($$source: Partial<SSHClosedPayload> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHClosedPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHClosedPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHClosedPayload($$parsedSource as Partial<SSHClosedPayload>);
    }
}

export class SSHDataPayload {
    "id": string;
    "data": string;

    /** Creates a new SSHDataPayload instance. */
    constructor($$source: Partial<SSHDataPayload> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHDataPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHDataPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHDataPayload($$parsedSource as Partial<SSHDataPayload>);
    }
}

export class SyncErrorPayload {
    "error": string;

    /** Creates a new SyncErrorPayload instance. */
    constructor($$source: Partial<SyncErrorPayload> = {}) {
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncErrorPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncErrorPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncErrorPayload($$parsedSource as Partial<SyncErrorPayload>);
    }
}
