// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppSettings {
    "language": string;
    "theme": string;
    "sync_method": string;
    "webdav_url": string;
    "webdav_username": string;
    "webdav_password": string;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("language" in $$source)) {
            this["language"] = "";
        }

        if (!("theme" in $$source)) {
            this["theme"] = "";
        }

        if (!("sync_method" in $$source)) {
            this["sync_method"] = "";
        }

        if (!("webdav_url" in $$source)) {
            this["webdav_url"] = "";
        }

        if (!("webdav_username" in $$source)) {
            this["webdav_username"] = "";
        }

        if (!("webdav_password" in $$source)) {
            this["webdav_password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}
