// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * GitHubReleaseInfo GitHub Release 信息
 */
export class GitHubReleaseInfo {
    "hasUpdate": boolean;
    "latestVersion": string;
    "currentVersion": string;
    "publishedAt": string;
    "releaseNotes": string;
    "htmlUrl": string;

    /**
     * Assets 发布资产，供前端展示可下载的安装包及其校验和文件
     */
    "assets": ReleaseAsset[];

    /** Creates a new GitHubReleaseInfo instance. */
    constructor($$source: Partial<GitHubReleaseInfo> = {}) {
        if (!("hasUpdate" in $$source)) {
            this["hasUpdate"] = false;
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("publishedAt" in $$source)) {
            this["publishedAt"] = "";
        }
        if (!("releaseNotes" in $$source)) {
            this["releaseNotes"] = "";
        }
        if (!("htmlUrl" in $$source)) {
            this["htmlUrl"] = "";
        }
        if (!("assets" in $$source)) {
            this["assets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubReleaseInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubReleaseInfo {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField6_0($$parsedSource["assets"]);
        }
        return new GitHubReleaseInfo($$parsedSource as Partial<GitHubReleaseInfo>);
    }
}

/**
 * ReleaseAsset GitHub Release 中的可下载资产。
 */
export class ReleaseAsset {
    "name": string;
    "browser_download_url": string;
    "size": number;

    /** Creates a new ReleaseAsset instance. */
    constructor($$source: Partial<ReleaseAsset> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("browser_download_url" in $$source)) {
            this["browser_download_url"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReleaseAsset instance from a string or object.
     */
    static createFrom($$source: any = {}): ReleaseAsset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReleaseAsset($$parsedSource as Partial<ReleaseAsset>);
    }
}

export class UpdateInfo {
    "isAvailable": boolean;
    "version": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("isAvailable" in $$source)) {
            this["isAvailable"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

// Private type creation functions
const $$createType0 = ReleaseAsset.createFrom;
const $$createType1 = $Create.Array($$createType0);
