// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyAndRestart(): $CancellablePromise<void> {
    return $Call.ByID(3937269583);
}

export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(612852608).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CheckGitHubReleases(): $CancellablePromise<$models.GitHubReleaseInfo | null> {
    return $Call.ByID(158079014).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DownloadUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3010458000);
}

export function OpenReleasePage(url: string): $CancellablePromise<void> {
    return $Call.ByID(2057714281, [url]);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType3 = $models.GitHubReleaseInfo.createFrom;
const $$createType2 = $Create.Nullable($$createType3);
