// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileEntry 描述远程文件系统中的一个条目（文件或目录）。
 */
export class FileEntry {
    /**
     * 条目名称（不含路径）
     */
    "name": string;

    /**
     * 字节数，目录通常为 0
     */
    "size": number;

    /**
     * 权限字符串，如 "drwxr-xr-x"
     */
    "mode": string;

    /**
     * 修改时间，RFC3339 格式
     */
    "modTime": string;

    /**
     * 是否为目录
     */
    "isDir": boolean;

    /**
     * 是否为符号链接
     */
    "isSymlink": boolean;

    /** Creates a new FileEntry instance. */
    constructor($$source: Partial<FileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("isSymlink" in $$source)) {
            this["isSymlink"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry($$parsedSource as Partial<FileEntry>);
    }
}

/**
 * SearchResultEntry 描述搜索结果中的一个条目，包含完整路径。
 */
export class SearchResultEntry {
    /**
     * 完整路径
     */
    "path": string;

    /**
     * 文件名（不含路径）
     */
    "name": string;

    /**
     * 字节数
     */
    "size": number;

    /**
     * 是否为目录
     */
    "isDir": boolean;

    /** Creates a new SearchResultEntry instance. */
    constructor($$source: Partial<SearchResultEntry> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResultEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResultEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResultEntry($$parsedSource as Partial<SearchResultEntry>);
    }
}
