// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SftpService 提供 SFTP 文件管理能力，作为 Wails 服务注册。
 * 它不持有连接本身，而是通过 SshService 按需获取（懒加载的）SFTP 客户端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Chmod 修改远程文件/目录的权限位。
 * mode 为标准的 os.FileMode 权限位（如 0755），传入时为 uint32。
 */
export function Chmod(sessionID: string, path: string, mode: number): $CancellablePromise<void> {
    return $Call.ByID(1505661080, sessionID, path, mode);
}

/**
 * DownloadFile 将远程文件下载到本地路径。
 * 与 UploadFile 对称：分块复制并推送进度，同样写入 "<localPath>.terminator-part-<总字节数>"
 * 以支持断点续传，完成后原子重命名到 localPath。
 */
export function DownloadFile(sessionID: string, transferID: string, remotePath: string, localPath: string): $CancellablePromise<void> {
    return $Call.ByID(3219845717, sessionID, transferID, remotePath, localPath);
}

/**
 * HomeDir 返回远程用户的家目录。
 * SFTP 登录后当前工作目录通常即家目录，Getwd 即可获取。
 */
export function HomeDir(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(2880722651, sessionID);
}

/**
 * ListDir 列出指定远程目录下的所有条目。
 * 返回的列表按名称排序（sftp.ReadDir 已排序），不包含 "." 与 ".."。
 */
export function ListDir(sessionID: string, path: string): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(122728374, sessionID, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Mkdir 在远程创建单个目录。父目录必须已存在。
 */
export function Mkdir(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(3831651222, sessionID, path);
}

/**
 * ReadFile 读取远程小文件内容并以字符串返回，用于文本预览。
 * 为避免内存溢出，限制最大读取 maxReadFileSize（1MB）字节；超出则返回错误。
 */
export function ReadFile(sessionID: string, path: string): $CancellablePromise<string> {
    return $Call.ByID(872684653, sessionID, path);
}

/**
 * Remove 删除远程文件或空目录。
 * 通过 Stat 判断类型后分别调用 Remove（文件）或 RemoveDirectory（空目录）。
 */
export function Remove(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(2937593491, sessionID, path);
}

/**
 * Rename 重命名或移动远程文件/目录。
 * 优先使用 PosixRename（原子操作），不支持时回退到普通 Rename。
 */
export function Rename(sessionID: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(4146034469, sessionID, oldPath, newPath);
}

/**
 * SearchFiles 递归搜索远程文件系统中的文件/目录。
 * searchPath 为搜索起始目录，query 为搜索关键词（匹配文件名）。
 * maxResults 限制返回结果数量，0 表示使用默认值 200。
 * 使用 find 命令实现，比递归 SFTP ListDir 快数十倍。
 */
export function SearchFiles(sessionID: string, searchPath: string, query: string, maxResults: number): $CancellablePromise<$models.SearchResultEntry[]> {
    return $Call.ByID(2705080646, sessionID, searchPath, query, maxResults).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * UploadFile 将本地文件上传到远程路径。
 * 该方法是同步的（Wails 绑定调用），但会通过 emitter 持续推送传输进度，
 * 前端可据 transferID 关联进度事件。传输结束（无论成功失败）推送完成事件。
 * 
 * 支持断点续传：数据先写入 "<remotePath>.terminator-part-<总字节数>"，中断时该文件保留，
 * 重试时按已有大小从断点继续；全部写完后才原子重命名到 remotePath，
 * 因此目标路径不会出现半截文件。续传假定源文件在两次尝试之间未改动。
 */
export function UploadFile(sessionID: string, transferID: string, localPath: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(890062900, sessionID, transferID, localPath, remotePath);
}

/**
 * WriteFile 将文本内容写入远程文件（覆盖写入），用于远程文件编辑保存。
 * 保留原文件权限；写入失败时不影响原文件内容（先写临时文件再重命名）。
 */
export function WriteFile(sessionID: string, path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1521240084, sessionID, path, content);
}

// Private type creation functions
const $$createType0 = $models.FileEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SearchResultEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
