// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2018517502, id);
}

/**
 * GenerateKey 生成 SSH 私钥
 * keyType: "ed25519" 或 "rsa"
 * rsaBits: RSA 密钥位数（2048 或 4096），Ed25519 忽略此参数
 * 返回 OpenSSH 格式的私钥（PEM 编码）
 */
export function GenerateKey(keyType: string, rsaBits: number): $CancellablePromise<string> {
    return $Call.ByID(402982813, keyType, rsaBits);
}

export function GetAll(): $CancellablePromise<$models.SavedKey[]> {
    return $Call.ByID(2217667998).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Save(key: $models.SavedKey): $CancellablePromise<string> {
    return $Call.ByID(2642404940, key);
}

// Private type creation functions
const $$createType0 = $models.SavedKey.createFrom;
const $$createType1 = $Create.Array($$createType0);
