// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Host {
    "id": string;
    "type": ItemType;
    "name": string;
    "group"?: string;
    "host": string;
    "port": number;
    "username": string;
    "password"?: string;
    "keyId"?: string;

    /**
     * 跳板机 Host ID，支持 SSH 多跳
     */
    "jumpHostId"?: string;

    /**
     * 代理配置（可选）
     * "http" | "socks5" | "" (无代理)
     */
    "proxyType"?: string;
    "proxyHost"?: string;
    "proxyPort"?: number;
    "proxyUsername"?: string;
    "proxyPassword"?: string;

    /**
     * SSH Agent 转发（可选）
     */
    "agentForwarding"?: boolean;

    /** Creates a new Host instance. */
    constructor($$source: Partial<Host> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Host instance from a string or object.
     */
    static createFrom($$source: any = {}): Host {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Host($$parsedSource as Partial<Host>);
    }
}

export enum ItemType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeHost = "host",
    TypeKey = "key",

    /**
     * 代码片段类型
     */
    TypeSnippet = "snippet",
};

export class SavedKey {
    "id": string;
    "type": ItemType;
    "name": string;
    "privateKey": string;

    /** Creates a new SavedKey instance. */
    constructor($$source: Partial<SavedKey> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("privateKey" in $$source)) {
            this["privateKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedKey instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedKey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedKey($$parsedSource as Partial<SavedKey>);
    }
}

/**
 * Snippet 表示一条可复用的代码片段/快捷命令
 */
export class Snippet {
    "id": string;
    "type": ItemType;
    "name": string;
    "group"?: string;
    "command": string;

    /** Creates a new Snippet instance. */
    constructor($$source: Partial<Snippet> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snippet instance from a string or object.
     */
    static createFrom($$source: any = {}): Snippet {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Snippet($$parsedSource as Partial<Snippet>);
    }
}
