// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as io$0 from "../../../io/models.js";

/**
 * Client represents an SFTP session on a *ssh.ClientConn SSH connection.
 * Multiple Clients can be active on a single SSH connection, and a Client
 * may be called concurrently from multiple Goroutines.
 * 
 * Client implements the github.com/kr/fs.FileSystem interface.
 */
export class Client {
    "Reader": io$0.Reader;
    "WriteCloser": io$0.WriteCloser;

    /** Creates a new Client instance. */
    constructor($$source: Partial<Client> = {}) {
        if (!("Reader" in $$source)) {
            this["Reader"] = null;
        }
        if (!("WriteCloser" in $$source)) {
            this["WriteCloser"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Client instance from a string or object.
     */
    static createFrom($$source: any = {}): Client {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Client($$parsedSource as Partial<Client>);
    }
}
