// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conflicts.sql

package dbgen

import (
	"context"
)

const countConflicts = `-- name: CountConflicts :one
SELECT COUNT(*) FROM sync_conflicts
`

func (q *Queries) CountConflicts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConflicts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteConflict = `-- name: DeleteConflict :exec
DELETE FROM sync_conflicts
WHERE blob_id = ?
`

func (q *Queries) DeleteConflict(ctx context.Context, blobID string) error {
	_, err := q.db.ExecContext(ctx, deleteConflict, blobID)
	return err
}

const getConflict = `-- name: GetConflict :one
SELECT blob_id, local_blob, remote_blob, local_updated_at, remote_updated_at,
       local_deleted, remote_deleted, detected_at
FROM sync_conflicts
WHERE blob_id = ?
`

func (q *Queries) GetConflict(ctx context.Context, blobID string) (SyncConflict, error) {
	row := q.db.QueryRowContext(ctx, getConflict, blobID)
	var i SyncConflict
	err := row.Scan(
		&i.BlobID,
		&i.LocalBlob,
		&i.RemoteBlob,
		&i.LocalUpdatedAt,
		&i.RemoteUpdatedAt,
		&i.LocalDeleted,
		&i.RemoteDeleted,
		&i.DetectedAt,
	)
	return i, err
}

const listConflicts = `-- name: ListConflicts :many
SELECT blob_id, local_blob, remote_blob, local_updated_at, remote_updated_at,
       local_deleted, remote_deleted, detected_at
FROM sync_conflicts
ORDER BY detected_at DESC
`

func (q *Queries) ListConflicts(ctx context.Context) ([]SyncConflict, error) {
	rows, err := q.db.QueryContext(ctx, listConflicts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncConflict
	for rows.Next() {
		var i SyncConflict
		if err := rows.Scan(
			&i.BlobID,
			&i.LocalBlob,
			&i.RemoteBlob,
			&i.LocalUpdatedAt,
			&i.RemoteUpdatedAt,
			&i.LocalDeleted,
			&i.RemoteDeleted,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConflict = `-- name: UpsertConflict :exec
INSERT INTO sync_conflicts (
    blob_id, local_blob, remote_blob, local_updated_at, remote_updated_at,
    local_deleted, remote_deleted, detected_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(blob_id) DO UPDATE SET
    local_blob = excluded.local_blob,
    remote_blob = excluded.remote_blob,
    local_updated_at = excluded.local_updated_at,
    remote_updated_at = excluded.remote_updated_at,
    local_deleted = excluded.local_deleted,
    remote_deleted = excluded.remote_deleted,
    detected_at = excluded.detected_at
`

type UpsertConflictParams struct {
	BlobID          string
	LocalBlob       string
	RemoteBlob      string
	LocalUpdatedAt  string
	RemoteUpdatedAt string
	LocalDeleted    bool
	RemoteDeleted   bool
	DetectedAt      string
}

func (q *Queries) UpsertConflict(ctx context.Context, arg UpsertConflictParams) error {
	_, err := q.db.ExecContext(ctx, upsertConflict,
		arg.BlobID,
		arg.LocalBlob,
		arg.RemoteBlob,
		arg.LocalUpdatedAt,
		arg.RemoteUpdatedAt,
		arg.LocalDeleted,
		arg.RemoteDeleted,
		arg.DetectedAt,
	)
	return err
}

const wipeConflicts = `-- name: WipeConflicts :exec
DELETE FROM sync_conflicts
`

func (q *Queries) WipeConflicts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, wipeConflicts)
	return err
}
