// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
)

type EncryptedBlob struct {
	ID        string
	Blob      string
	UpdatedAt string
	IsDeleted bool
}

type SyncConflict struct {
	BlobID          string
	LocalBlob       string
	RemoteBlob      string
	LocalUpdatedAt  string
	RemoteUpdatedAt string
	LocalDeleted    bool
	RemoteDeleted   bool
	DetectedAt      string
}

type User struct {
	ID                 string
	Username           string
	KeySalt            string
	AuthSalt           sql.NullString
	EncryptedMasterKey string
	ServerUrl          sql.NullString
	LastSyncTime       sql.NullString
}
