// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WebDAVService 暴露给前端的 WebDAV 配置管理服务。
 * WebDAV 配置存储在 settings.json（AppSettings），不存 DB。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetWebDAVConfig 获取 WebDAV 配置，出于安全考虑不返回密码
 */
export function GetWebDAVConfig(): $CancellablePromise<[string, string]> {
    return $Call.ByID(880668331);
}

/**
 * SaveWebDAVConfig 保存 WebDAV 配置到 settings.json，并将同步方式切换为 webdav。
 * 密码明文存储在 settings.json（和网盘密码一样，用户自己负责）。
 * 如果 password 为空，保留原有密码（编辑配置时不强制重新输入密码）。
 */
export function SaveWebDAVConfig(url: string, username: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(276154702, url, username, password);
}

/**
 * TestWebDAVConnection 测试 WebDAV 连接是否可用（前端调用，无需解锁 vault）
 */
export function TestWebDAVConnection(url: string, username: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(2360136853, url, username, password);
}
