// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DisconnectCloud removes the cloud server association from the local vault.
 * The vault stays unlocked and all data remains; only the server URL is
 * cleared and the auth token discarded. Auto-sync should be stopped by the
 * caller (SyncService.StopAutoSync) before invoking this.
 */
export function DisconnectCloud(): $CancellablePromise<void> {
    return $Call.ByID(3716161388);
}

export function GetCurrentUser(): $CancellablePromise<$models.UserInfo | null> {
    return $Call.ByID(3254285799).then(($result: any) => {
        return $$createType1($result);
    });
}

export function HasUser(): $CancellablePromise<boolean> {
    return $Call.ByID(412997436);
}

export function LockVault(): $CancellablePromise<void> {
    return $Call.ByID(2757158698);
}

/**
 * Login - "unlock vault"
 * 
 * 外层负责失败退避，真正的校验逻辑在 login 中。
 */
export function Login(password: string): $CancellablePromise<void> {
    return $Call.ByID(1321617150, password);
}

/**
 * LoginFromSync - "connect and restore"
 */
export function LoginFromSync(serverUrl: string, username: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(259731729, serverUrl, username, password);
}

export function RegisterLocal(username: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(1530550495, username, password);
}

export function RegisterOnServer(serverURL: string): $CancellablePromise<void> {
    return $Call.ByID(2102841450, serverURL);
}

/**
 * SetSessionDisconnector 注入 SSH 服务引用，用于 WipeData 时断开所有连接
 */
export function SetSessionDisconnector(d: $models.SessionDisconnector): $CancellablePromise<void> {
    return $Call.ByID(3784343510, d);
}

/**
 * SetSyncPauser 注入同步服务引用，用于 WipeData 时暂停后台同步。
 * 否则在途同步会把擦除前的旧条目推送到服务器，导致已清除的数据残留在云端。
 */
export function SetSyncPauser(p: $models.SyncPauser): $CancellablePromise<void> {
    return $Call.ByID(692209416, p);
}

export function WipeData(): $CancellablePromise<void> {
    return $Call.ByID(132727258);
}

// Private type creation functions
const $$createType0 = $models.UserInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
