// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SessionDisconnector 断开所有 SSH 会话的接口（避免循环依赖）
 */
export type SessionDisconnector = any;

/**
 * SyncPauser 暂停后台同步的接口（避免循环依赖）。
 * 擦除会整体清空本地数据，必须确保期间没有同步在跑。
 */
export type SyncPauser = any;

export class UserInfo {
    "username": string;
    "serverUrl": string;

    /** Creates a new UserInfo instance. */
    constructor($$source: Partial<UserInfo> = {}) {
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("serverUrl" in $$source)) {
            this["serverUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UserInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserInfo($$parsedSource as Partial<UserInfo>);
    }
}
