// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BackupFileInfo 备份文件摘要，供导入前向用户确认内容。
 */
export class BackupFileInfo {
    "fileName": string;
    "username": string;
    "appVersion": string;
    "exportedAt": string;
    "itemCount": number;

    /** Creates a new BackupFileInfo instance. */
    constructor($$source: Partial<BackupFileInfo> = {}) {
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("appVersion" in $$source)) {
            this["appVersion"] = "";
        }
        if (!("exportedAt" in $$source)) {
            this["exportedAt"] = "";
        }
        if (!("itemCount" in $$source)) {
            this["itemCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupFileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupFileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupFileInfo($$parsedSource as Partial<BackupFileInfo>);
    }
}
